/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "01_MCAL/00_RCC/RCC_interface.h"
#include "01_MCAL/01_GPIO/GPIO_interface.h"
#include "02_HAL/01_LCD/LCD_interface.h"



int main(void)
{
    /* Loop forever */

	/* GPIOC clk EN*/
	MRCC_voidEnableClock(AHB1, 0);
	/* GPIOC clk EN*/
	MRCC_voidEnableClock(AHB1, 2);

	for(int i =0; i<8; i++){
		MGPIO_vSetPinMode(GPIOA_PORT, i, OUTPUT);
		MGPIO_vSetOutputType(GPIOA_PORT, i, PUSH_PULL);
		MGPIO_vSetPullType(GPIOA_PORT, i, NORMAL);
		MGPIO_vSetPinOutSpeed(GPIOA_PORT, i, LOW_SPEED);
	}

	for(int i =5; i<=7; i++){
		MGPIO_vSetPinMode(GPIOC_PORT, i, OUTPUT);
		MGPIO_vSetOutputType(GPIOC_PORT, i, PUSH_PULL);
		MGPIO_vSetPullType(GPIOC_PORT, i, NORMAL);
		MGPIO_vSetPinOutSpeed(GPIOC_PORT, i, LOW_SPEED);
	}
	LCD_vidInit();

	LCD_vidWriteString("Hello from STM");
	for(;;){

	}
}
